{{- if .Values.rbac.enabled -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ocsp-manager.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "ocsp-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ocsp-manager.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "ocsp-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ocsp-manager.fullname" . }}-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "ocsp-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
