name: Helm Publish

on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      # https://github.com/helm/chart-releaser-action
      #
      # git switch --orphan gh-pages
      # git commit --allow-empty -m "initial commit"
      # git push -u origin gh-pages
      #
      # set github pages source branch to gh-pages
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: stable
        env:
          CR_TOKEN: "${{ secrets.GHCR_PASSWORD }}"

